mozilla/fxa-js-client

tests/intern_sauce.js
@zaach or @vladikoff - could you give this a r?
We do not support IE8 and can safely disable the tests.
fixes #143
=> cleanup(test): Disable IE8 tests.

client/FxAccountClient.js, tests/lib/account.js, tests/mocks/request.js
* `accountUnlockResendCode` to send an unlock email
* `accountUnlockVerifyCode` to verify a code
* `accountLock` to lock an account, used only in testing.
fixes #134
Goes along with:
* https://github.com/mozilla/fxa-auth-db-server/pull/123
* https://github.com/mozilla/fxa-auth-db-mem/pull/11
* https://github.com/mozilla/fxa-auth-db-mysql/pull/7
* https://github.com/mozilla/fxa-auth-mailer/pull/23
* https://github.com/mozilla/fxa-content-server/pull/1806
* https://github.com/mozilla/fxa-auth-server/pull/867
=> feat(client): Add account unlock functionality.

client/FxAccountClient.js, tests/lib/signIn.js
@zaach  or @vladikoff - could you give an initial r? The backend and front end portions are not yet ready.
Used for account notifications. If `service===sync`, a notification email is sent to the user.
fixes #145
Link to:
https://github.com/mozilla/fxa-auth-mailer/pull/26
https://github.com/mozilla/fxa-auth-server/pull/876
https://github.com/mozilla/fxa-content-server/pull/2129
=> feat(client): signIn can now pass along a `service` option.

client/FxAccountClient.js, tests/lib/signIn.js
@vladikoff or @zaach - r?
`reason` will be used along with `service` on the auth server to decide when to send notification emails.
fixes #150
=> feat(client): Pass along `reason` in `signIn`

client/lib/request.js, tests/lib/request.js
=> fix(request): Return rejected promise immediately if xhr.open() fails

client/FxAccountClient.js
I thought `context` when calling `hawkCredentials` was a human readable description instead of one of `sessionToken`, `passwordForgotToken`, or `accountResetToken`.
=> fix(client): Send `sessionToken` as the `context` when creating Hawk creds.

client/FxAccountClient.js, tests/all.js, tests/lib/device.js, tests/lib/push-constants.js, tests/lib/signIn.js, tests/lib/signUp.js, tests/mocks/request.js
This is a follow on to #177 to add `devices` options to `signIn` and `signUp`. To be merged once the auth-server portion of this functionality is ready.
=> feat(client): Add "devices API" options to signIn and signUp

client/FxAccountClient.js, tests/lib/account.js
This PR adds the ability to query account status by email to the client script. It uses the auth endpoint [/v1/account/status](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-v1accountstatus).
This supports https://github.com/mozilla/fxa-content-server/pull/3537
=> feat(client): Add new client function to get account status from options

client/FxAccountClient.js
Noticed that the device parameter docs were wrong when I was fixing up https://github.com/mozilla/fxa-js-client/pull/187#discussion_r55590795. This fixes them.
=> fix(docs): fix property hierarchy in device doc comments

client/FxAccountClient.js, client/lib/metricsContext.js, tests/lib/account.js, tests/lib/certificateSign.js, tests/lib/signIn.js, tests/lib/signUp.js
This change is to enable https://github.com/mozilla/fxa-content-server/issues/3551, propagation of metrics context metadata to the auth server for [FxA-70](https://github.com/mozilla/fxa/tree/master/features/FxA-70-kpi-dashboards).
~~Something I wasn't sure about: I call `Object.keys` and `Array.forEach` at one point, are they safe to use in this repo or does it need to be ES3-safe? Happy to replace them with an old-fashioned loop if necessary.~~
**EDIT:** This PR is dependent on https://github.com/mozilla/fxa-auth-server/pull/1213, it can't be merged until that one is.
=> feat(client): add optional metricsContext metadata

client/FxAccountClient.js, tests/lib/verifyCode.js
Allows passing a `service` parameter when verifying the email code; Connects to https://github.com/mozilla/fxa-auth-server/issues/1249
I added a "doesn't blow up when called with service parameter" test, but couldn't see a good way of testing the details of this - at least, not without adding code to intercept the HTTP request and check that `service` was included in the parameters.  Is that something I should try to do?
=> feat(client): verifyCode support for `service` parameter

client/FxAccountClient.js, tests/ci/travis-auth-server-test.sh, tests/lib/signIn.js
* signIn now accepts `redirectTo` and `resume` options.
Goes with https://github.com/mozilla/fxa-auth-server/pull/1275, https://github.com/mozilla/fxa-content-server/pull/3671
=> feat(client): signIn support signin confirmation

client/FxAccountClient.js, tests/lib/account.js, tests/lib/certificateSign.js
There are two changes here, both related to the discussion in https://github.com/mozilla/fxa-auth-server/issues/1345:
1. A `service` option is added to `certificateSign`, which adds a `service` parameter to the query string. This enables us to properly fix the issue of spurious placeholder devices discussed in https://github.com/mozilla/fxa-content-server/issues/3933.
2. The `metricsContext` option is removed from `accountReset` and `certificateSign`, as they're about to be removed from the auth server for https://github.com/mozilla/fxa-auth-server/issues/1345. I've verified that the content server never passes it to those methods and nor should other clients be doing that.
@shane-tomlinson, low-priority r?
=> Eliminate redundant payload data

client/FxAccountClient.js
This PR updates the fxa-client to send the session id instead of session data to the auth server. This fix does not require any updates to the content-server because existing pattern is to send session data to fxa-client. Auth-server changes to support this were merged [here](https://github.com/mozilla/fxa-auth-server/pull/1302)
Fixes https://github.com/mozilla/fxa-content-server/issues/3875
=> refactor(password): Send session id on password change

client/FxAccountClient.js, tests/lib/signIn.js
Since https://github.com/mozilla/fxa-auth-server/issues/1451 has landed, the auth-server ignores `sendEmailIfUnverified`.
=> refactor(signin): Remove `sendEmailIfUnverified` from client

client/FxAccountClient.js
Sorry, I forgot to update the doc comments when I removed the redundant metrics context properties in #223.
@vladikoff r?
=> fix(docs): remove old redundant metrics context properties

client/FxAccountClient.js, tests/lib/account.js
=> fix(client): propagate metrics context data to /account/reset

client/FxAccountClient.js, tests/all.js, tests/lib/sms.js, tests/mocks/request.js
This PR adds support for sending sms messages from the js client. The responses and request values will be changing as the api becomes defined.
Connects with https://github.com/mozilla/fxa-features/issues/53, https://github.com/mozilla/fxa-auth-server/issues/1628
=> feat(sms): Add support for sending sms messages

client/FxAccountClient.js, tests/lib/sms.js, tests/mocks/request.js
@philbooth - r?
issue mozilla/fxa-content-server#4861
blocks https://github.com/mozilla/fxa-content-server/pull/4872
=> feat(sms): Add a `country` option to `/sms/status` endpoint

client/FxAccountClient.js, tests/all.js, tests/lib/signinCodes.js, tests/mocks/request.js
Fixes #242. Matches the endpoint being added to the auth server in mozilla/fxa-auth-server#1906.
=> feat(client): implement consumeSigninCode for POST /signinCodes/consume

client/FxAccountClient.js, tests/addons/accountHelper.js, tests/lib/emails.js, tests/mocks/request.js
This PR adds support to the js client for checking whether or not secondary emails is enabled for a particular user. The feature is considered enabled if their email matches the regex on auth-server and if they are in a verified session.
=> feat(emails): Expose client endpoints for detecting if secondary emails

client/FxAccountClient.js, tests/lib/session.js, tests/lib/signUp.js, tests/lib/verifyCode.js
This skips the need for the auth-server to keep a fragile cache of opt-in intents. Blocked on https://github.com/mozilla/fxa-auth-server/pull/1984
=> feat(client): move marketingOptIn parameter to verifyCode

.travis.yml, client/FxAccountClient.js, client/lib/metricsContext.js, tests/lib/account.js, tests/lib/metricsContext.js, tests/lib/signUp.js
Related to mozilla/fxa-auth-server#2072.
Adds a `deviceId` property to `metricsContext`.
Includes a preliminary fix to disable node 4 tests against a real auth server instance, because the auth server doesn't run in node 4 any more. Of course we could just disable tests on node 4 entirely, too. But there's nothing in this repo that requires it, the mock tests could even run against 0.10 if we wanted?
=> feat(api): add deviceId to metricsContext data

client/FxAccountClient.js, tests/lib/recoveryEmail.js
=> feat(session): Pass `options.type` to recoveryEmailResendCode

client/FxAccountClient.js, tests/all.js, tests/lib/recoveryKeys.js, tests/mocks/request.js
blocked by https://github.com/mozilla/fxa-auth-server/issues/2421
=> feat(recovery): initial support for account recovery

client/FxAccountClient.js, tests/lib/recoveryKeys.js, tests/mocks/request.js
Connects to https://github.com/mozilla/fxa-content-server/pull/6203
This exposes the new endpoints added in https://github.com/mozilla/fxa-auth-server/pull/2518. It also updates the recovery key routes to be singular.
=> feat(recovery): add delete and check endpoints recovery keys

client/FxAccountClient.js, tests/lib/recoveryCodes.js, tests/lib/totp.js
Related to mozilla/fxa-auth-server#2496.
We're deprecating the `metricsContext` payload on a bunch of auth server routes, but first we must stop sending the data.  Ergo this PR.
=> fix(metrics): remove metricsContext from deprecated routes

client/lib/metricsContext.js, tests/lib/account.js, tests/lib/metricsContext.js, tests/lib/recoveryCodes.js, tests/lib/session.js
Related to mozilla/fxa-auth-server#2917.
Adds `entrypoint` to the metricsContext payload, which was added to the auth server in mozilla/fxa-auth-server#2929 and shipped in train 131. Also includes a secondary fix for the tests, where new validation in the auth server was causing them to fail.
=> chore(metrics): reinstate entrypoint to metricsContext payload
