- .eslintrc
- Gruntfile.js
- client/.eslintrc
- client/FxAccountClient.js
- client/lib/hawk.js
- client/lib/request.js
- package.json
- tasks/eslint.js
Fixes #156 
Switch from JSHint to ESLint
Add rules to ESLint
Also have JSHint in parallel
Add inline rules for ignoring complexity
@zaach 
@pdehaan
>  chore(lint): switch from JSHint to ESLint

- .jscsrc
- tasks/eslint.js
- tasks/jscs.js
- tests/.eslintrc
- tests/addons/accountHelper.js
- tests/addons/restmail.js
- tests/addons/sinonResponder.js
- tests/intern.js
- tests/intern_sauce.js
- tests/lib/account.js
- tests/lib/certificateSign.js
- tests/lib/errors.js
- tests/lib/headerLang.js
- tests/lib/passwordChange.js
- tests/lib/recoveryEmail.js
- tests/lib/request.js
- tests/lib/session.js
- tests/lib/signIn.js
- tests/lib/signUp.js
- tests/lib/unbundle.js
- tests/lib/verifyCode.js
- tests/mocks/request.js
Fixes #163
Lint the tests directory
Fix redundant jscs-eslint rules
@pdehaan 
@vladikoff
> chore(lint): Lint the tests directory

- tests/intern_sauce.js
> chore(tests): include Firefox 18 in SauceLabs tests

- tests/lib/account.js
Fixes https://github.com/mozilla/fxa-js-client/issues/166
> fix(tests): fix account.js tests

- client/FxAccountClient.js
- tests/all.js
- tests/lib/init.js
Fixes https://github.com/mozilla/fxa-js-client/issues/142
Fixes https://github.com/mozilla/fxa-js-client/issues/149
> fix(client): throw harder on bad client init

- client/FxAccountClient.js
- tests/all.js
- tests/lib/device.js
- tests/lib/push-constants.js
- tests/mocks/request.js
fixes #176
Early stage WIP, nowhere even close to being ready for feedback.
> feat(client): Add methods for working with the "devices" API.

- tests/lib/device.js
- tests/lib/signIn.js
- tests/lib/signUp.js
> fix(client): fix device tests against remote

- tests/lib/account.js
- tests/lib/recoveryEmail.js
- tests/mocks/request.js
> fix(tests): update tests to support welcome email

- client/FxAccountClient.js
- tests/lib/device.js
- tests/lib/push-constants.js
- tests/lib/signIn.js
- tests/lib/signUp.js
- tests/mocks/request.js
See https://github.com/mozilla/fxa-auth-server/pull/1229 for context
> feat(push): add support for AuthKey

- client/FxAccountClient.js
- tests/lib/signIn.js
Ref https://github.com/mozilla/fxa-content-server/pull/3671
Ref https://github.com/mozilla/fxa-auth-server/pull/1232
> feat(client): signIn support for `redirectTo` and `resume`

- .travis.yml
- tests/ci/travis-auth-server-test.sh
- tests/lib/account.js
- tests/lib/device.js
- tests/lib/headerLang.js
- tests/lib/recoveryEmail.js
- tests/lib/signIn.js
- tests/lib/signUp.js
- tests/mocks/request.js
> fix(tests): adds local fxa-auth-server testing

- client/FxAccountClient.js
- tests/lib/signIn.js
- tests/lib/signUp.js
- tests/mocks/request.js
> Issues 198 201 failing local tests

- client/FxAccountClient.js
- tests/lib/account.js
- tests/lib/passwordChange.js
- tests/mocks/request.js
@vbudhram - could you review this to ensure the call to /password/change/finish matches your expectations?
ref https://github.com/mozilla/fxa-content-server/pull/3715
> feat(client): Update changePassword to accept a sessionToken and a keys option

- client/FxAccountClient.js
- tests/lib/account.js
- tests/lib/verifyCode.js
- tests/mocks/request.js
Used with https://github.com/mozilla/fxa-auth-server/commit/aca4185a826a70e5fe57247490238e63ddce5ce0
> feat(metrics): pass the reminder param to account verification

- client/FxAccountClient.js
- tests/ci/travis-auth-server-test.sh
- tests/lib/account.js
- tests/mocks/errors.js
- tests/mocks/request.js
> feat(client): Add signin authorization support.

- client/FxAccountClient.js
Connects with https://github.com/mozilla/fxa-content-server/pull/4297
> feat(metrics): Add support for password reset events

- tests/lib/signUp.js
> fix(tests): add tests for data requested by xhr requests

- tests/intern.js
> chore(tests): adjust remote test urls

- tests/ci/travis-auth-server-test.sh
- tests/lib/signIn.js
Fixes the current bustage in CI. @vbudhram r?
> fix(tests): force sign-in confirmation for tests

- client/FxAccountClient.js
- tests/lib/signUp.js
Fixes #227
@shane-tomlinson r?
> refactor(preVerifyToken): remove preVerifyToken

- bower.json
- package.json
This is a journey to fix https://github.com/mozilla/fxa-content-server/issues/2160
@shane-tomlinson r?
> fix(deps): update to latest p-promise

- client/FxAccountClient.js
- tests/lib/misc.js
It didn't allow falsey values, and checked incorrectly for empty objects.
fixes #231
@philbooth - r?
> fix(client): Fix the required check.

- tests/lib/account.js
- tests/lib/passwordChange.js
this is for https://github.com/mozilla/fxa-auth-server/pull/1643
> fix(tests): make sure test work wit signin confirmation by default

- client/FxAccountClient.js
- tests/ci/travis-auth-server-test.sh
- tests/lib/session.js
- tests/mocks/request.js
Connects to https://github.com/mozilla/fxa-content-server/issues/4585
> feat(websessions): add support for the new web session api

- client/FxAccountClient.js
- tests/lib/sms.js
- tests/mocks/request.js
> feat(client): support GET /sms/status

- .travis.yml
- package.json
- tests/addons/node-client.js
- tests/ci/install-tunnel.sh
- tests/intern_sauce.js
- tests/lib/misc.js
My hope is this will fix the broken tunnel problem in https://travis-ci.org/mozilla/fxa-js-client/jobs/215557097
> feat(deps): Update intern-geezer to the newest version.

- .travis.yml
> chore(ci): run tests in node 6

- client/FxAccountClient.js
- tests/lib/account.js
- tests/lib/signinCodes.js
> fix(lib): never throw from promise-returning methods

- tests/ci/travis-auth-server-test.sh
New PR to test theory that auth-server needs a little more delay when starting, which was causing the flakiness.
Fixes #249
> feat(emails): Set test start delay to 10s

- client/FxAccountClient.js
- tests/lib/signUp.js
Related https://github.com/mozilla/fxa-bugzilla-mirror/issues/167
Seems server tests fail, I'm assuming until the auth-server PR is merged?
> feat(client): add marketingOptIn paramter for signUp

- .travis.yml
- client/FxAccountClient.js
- tests/addons/accountHelper.js
- tests/lib/account.js
- tests/lib/emails.js
- tests/lib/passwordChange.js
- tests/lib/session.js
- tests/mocks/request.js
Auth tests will fail until https://github.com/mozilla/fxa-auth-server/pull/1983 is merged
> feat(emails): Add support for changing primary email

- tests/lib/emails.js
This PR fixes tests that got broken from https://github.com/mozilla/fxa-auth-server/pull/2121.
> fix(test): Fixed broken email tests

- client/FxAccountClient.js
- client/lib/metricsContext.js
- tests/lib/account.js
- tests/lib/metricsContext.js
- tests/lib/signUp.js
Related to mozilla/fxa-content-server#5487.
> feat(api): add utm params to metrics context

- client/FxAccountClient.js
- tests/lib/emails.js
- tests/mocks/request.js
Connects to https://github.com/mozilla/fxa-auth-server/issues/2224
> chore(emails): remove logic to check for secondary email feature

- client/FxAccountClient.js
- tests/all.js
- tests/lib/tokenCodes.js
- tests/mocks/request.js
Connects with https://github.com/mozilla/fxa-content-server/pull/5706
> feat(tokens): add verify token code support

- client/FxAccountClient.js
- package.json
- tests/all.js
- tests/lib/totp.js
- tests/mocks/request.js
Connects to https://github.com/mozilla/fxa-content-server/issues/5863
A WIP PR for client side functions needed for TOTP.
> feat(totp): totp client-side management apis

- client/FxAccountClient.js
- tests/all.js
- tests/lib/recoveryCodes.js
- tests/lib/tokenCodes.js
- tests/lib/totp.js
- tests/mocks/request.js
Connects to https://github.com/mozilla/fxa-content-server/issues/5865
> feat(recovery): add recovery code endpoints

- .gitignore
- client/FxAccountClient.js
- tests/lib/account.js
- tests/lib/recoveryEmail.js
- tests/lib/session.js
- tests/lib/signIn.js
- tests/lib/signUp.js
Connects with https://github.com/mozilla/fxa-auth-server/issues/2312
Tests blocked on https://github.com/mozilla/fxa-auth-server/pull/2405
> feat(session): support account delete with session token

- package.json
> source-1.0.6

- package.json
- tests/intern_sauce.js
> chore(release): Merge source-1.0.7 into master

- package.json
> Merge 1.0.8 tag into master
